# fly.toml app configuration file generated for part3-fso on 2024-02-14T00:47:31+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'part3-fso'
primary_region = 'syd'

[env]
  PORT = "3000" # add this

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
